# Generated by Django 3.1.3 on 2020-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='check.TagModel', verbose_name='タグ名'),
        ),
    ]
