# Generated by Django 3.1.3 on 2020-11-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_tagmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='QestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('es', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.esmodel')),
                ('tags', models.ManyToManyField(to='check.TagModel')),
            ],
        ),
    ]
